Exception in thread "main" java.lang.RuntimeException
	at Test.main(Test.java:7)
